spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/examplewebservice
    username: postgres
    password: java
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  error:
    include-message: always
    include-binding-errors: always